services:
  - type: web
    name: predictive-maintenance
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fbackend.mysite.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        value: <your_secret_key>
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        value: <your_render_postgres_url>
