# Generated by Django 5.1.7 on 2025-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mach_type', models.CharField(max_length=1)),
                ('air_temp', models.FloatField()),
                ('process_temp', models.FloatField()),
                ('rot_speed', models.IntegerField()),
                ('torque', models.FloatField()),
                ('tool_wear', models.IntegerField()),
                ('faliure_risk', models.FloatField()),
                ('failure_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
